name: Flutter Unit Tests

on:
  push:
    branches:
      - test

jobs:
  unit-test:
    name: Run Flutter Unit Tests
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Generate files with build_runner
        run: dart run build_runner build --delete-conflicting-outputs  

      # 🧪 Run Unit Tests
      - name: Run Unit Tests
        run: |
          flutter test $(find test/unit -name "*.dart" ! -name "*.mocks.dart") --coverage
          mkdir -p test-results/unit
          cp coverage/lcov.info test-results/unit/lcov.info
        shell: /bin/bash -e {0}
        env:
          FLUTTER_ROOT: /Users/runner/hostedtoolcache/flutter/stable-3.27.0-arm64
          PUB_CACHE: /Users/runner/.pub-cache

      # 📤 Upload Unit Test Results
      - name: Upload Unit Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Unit Test Coverage Report
          path: test-results/unit
