name: Flutter Unit Tests

on:
  push:
    branches:
      - main

jobs:
  unit-test:
    name: Run Flutter Unit Tests
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'

      - name: Install dependencies
        run: flutter pub get

      # 🧪 Run Unit Tests
      - name: Run Unit Tests
        run: |
          flutter test/unit --coverage
          mkdir -p test-results/unit
          cp coverage/lcov.info test-results/unit/lcov.info

      # 📤 Upload Unit Test Results
      - name: Upload Unit Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Unit Test Coverage Report
          path: test-results/unit
