name: Upload Flutter APK to Google Play Console

on:
  push:
    branches:
      - main  # Trigger this workflow on push to the main branch

jobs:
  upload:
    name: Build & Upload Flutter APK to Google Play Console
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.0'  # Use the version of Flutter you want

    - name: Install dependencies
      run: flutter pub get  # Install Flutter dependencies

        #5 Setup Keystore
    - name: Decode Keystore
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/keystore.jks
          
    - name: Create key.properties
      run: |
        echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
        echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
        echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
        echo "storeFile=keystore.jks" >> android/key.properties

    - name: Build AppBundle
      run: flutter build appbundle # Builds the aap-bundle for release

    - name: Upload to Google Play
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJson: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT }}  # Set this secret in your GitHub repo
        packageName: com.sptpra.fitness_thoughts  # Replace with your app's package name
        releaseFiles: build/app/outputs/bundle/release/app-release.aab  # Path to your aab
        track: production  # Can be 'alpha', 'beta', 'production', etc 
