name: Build web

on:
  push:
    branches:
      - production_web  # Trigger this workflow on push to the main branch

jobs:
  upload:
    name: Build web
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.0'  # Use the version of Flutter you want

    - name: Install dependencies
      run: flutter pub get  # Install Flutter dependencies

    - name: Build web
      run: flutter build web --wasm --no-tree-shake-icons

        #9 Upload Artifacts
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Releases
        path: |
          build/web
        # mappingFile: app/build/outputs/mapping/release/mapping.txt
        # debugSymbols: app/intermediates/merged_native_libs/release/out/lib
