name: Flutter Widget Tests

on:

  push:
    branches:
      - test

jobs:
  widget-test:
    name: Run Flutter Widget Tests
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Run Widget Tests
        run: 
            flutter test $(find test/widget -name "*.dart") --coverage
            mkdir -p test-results/widget
            cp coverage/lcov.info test-results/widget/lcov.info

      - name: Upload Widget Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Widget Test Coverage Report
          path: test-results/widget
